### ISSUE TITLE
which upload sites should I use? That won't delete my file?

### ISSUE THREAD

**Issue by Anox208** [UnamSanctam/UnamDownloader#2]
anonfiles? or do have anything that is better?

**Comment by UnamSanctam** [comment]
Not anonfiles since their direct download URL changes all the time. Usually the best ones are git services like BitBucket or other ones but they are usually hard to use if you don't know how to use git. You can also use things like Discord to host files, create a new account and then a new server (or DM another throwaway account), then you can upload a file there and right-click it and choose "Copy Link". I believe Discord links shouldn't change and usually they don't get removed so that might work well.
