### ISSUE TITLE
Binder

### ISSUE THREAD

**Issue by samogost** [UnamSanctam/UnamDownloader#60]
If unamdownloader downloads files via URL and executes them silently, why don't you add file binding? same as unambinder but can download files via URL. Can you add it to the next update? 🤔

**Comment by samogost** [comment]
> If unamdownloader downloads files via URL and executes them silently, why don't you add file binding? same as unambinder but can download files via URL. Can you add it to the next update? 🤔

Because when opening the payload, it takes a long time for the software to appear, perhaps because the first file takes time to download. Because of that, I hope you can add the binder in the next update.

**Comment by samogost** [comment]
The fact that the software does not show up causes the victim to lose patience and open it many times, which is even worse if the victim's computer has a poor wifi connection.

**Comment by samogost** [comment]
it will be great if you add it in the next update 👍

**Comment by UnamSanctam** [comment]
Not sure what you're asking for, but if you want normal file binding and also file downloading from a URL then you can just first build a build with the downloader and then use the binder on that file. The reason they are separated is because they use entirely different philosophies, the binder stores the bytes in the file and then performs many things with the files using the Windows API while the downloader is just a shell for a powershell command.

**Comment by samogost** [comment]
> Not sure what you're asking for, but if you want normal file binding and also file downloading from a URL then you can just first build a build with the downloader and then use the binder on that file. The reason they are separated is because they use entirely different philosophies, the binder stores the bytes in the file and then performs many things with the files using the Windows API while the downloader is just a shell for a powershell command.

okay, thank you.
