### ISSUE TITLE
direct download link question

### ISSUE THREAD

**Issue by picklejohndoe** [UnamSanctam/UnamDownloader#80]
would the downloader keep trying to download until it's able to download? because lots of direct download file hosting places have restrictions on how much can be downloaded per day

**Comment by UnamSanctam** [comment]
No it doesn't retry multiple times, you can see the code it generates here: https://github.com/UnamSanctam/UnamDownloader/blob/3deb02a9e38dea2c11c11dcd502b3d6c4c42fe1e/UnamDownloader/Forms/Builder.cs#L184
It would be possible to add that, but it might not be too good since it would both increase the complexity of the command and would also keep the powershell process running until it completes the download.
